# Si existe la tabla que la actualice si no existe que la cree para eso sirve la linea 2
spring.jpa.hibernate.ddl-auto=update    
spring.application.name=apirest

server.port=8080
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATA_SOURCE_URL}
spring.datasource.username=${SPRING_DATA_SOURCE_USERNAME}
spring.datasource.password=${SPRING_DATA_SOURCE_PASSWORD}